# Generated by Django 4.2.3 on 2023-08-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0002_alter_bank_account_accountnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(blank=True, choices=[('debit', 'debit'), ('credit', 'credit')], max_length=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank_Account.bank_account')),
            ],
        ),
    ]
