# Generated by Django 4.2.4 on 2023-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0003_accounting_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='accountNumber',
            field=models.CharField(max_length=16),
        ),
    ]
