# Generated by Django 4.2.4 on 2023-09-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0004_alter_bank_account_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='accountNumber',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
