# Generated by Django 4.2.4 on 2023-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0005_alter_bank_account_accountnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting_document',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
