# Generated by Django 4.2.4 on 2023-09-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0006_accounting_document_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting_document',
            name='remaining',
            field=models.IntegerField(null=True),
        ),
    ]
