# Generated by Django 4.2.4 on 2023-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0007_accounting_document_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting_document',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
