# Generated by Django 4.2.4 on 2023-09-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0008_alter_accounting_document_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting_document',
            name='type',
            field=models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=20, null=True),
        ),
    ]
