# Generated by Django 4.2.4 on 2023-09-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0009_alter_accounting_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting_document',
            name='remaining',
        ),
    ]
