# Generated by Django 4.2.4 on 2023-09-15 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0012_alter_accounting_document_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
