# Generated by Django 4.2.4 on 2023-10-06 16:46

from django.db import migrations
from django_jalali.db import models as jmodel


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Account', '0013_alter_bank_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting_document',
            name='datetime',
            field=jmodel.jDateTimeField(null=True),
        ),
    ]
